Document: smedit
Title: Debian smedit Manual
Author: <insert document author here>
Abstract: This manual describes what smedit is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/smedit/smedit.sgml.gz

Format: postscript
Files: /usr/share/doc/smedit/smedit.ps.gz

Format: text
Files: /usr/share/doc/smedit/smedit.text.gz

Format: HTML
Index: /usr/share/doc/smedit/html/index.html
Files: /usr/share/doc/smedit/html/*.html
