#pragma once

#include <string>

#include "historymanager/operation.h"
#include "models/machine.h"
#include "models/project.h"


class MachineChgOperation : public Operation
{
    public:
        MachineChgOperation(Machine* machine);
        unsigned int execute(Project& project);
        virtual void execute_impl(Machine* machine)=0;

    protected:
        unsigned int machine_id;    
};


class OpMachineCreate : public Operation
{
    public:
        OpMachineCreate(string name);
        unsigned int execute(Project& project);
        OpMachineCreate* clone();

    private:
        string name;
};


class OpMachineDelete : public Operation
{
    public:
        OpMachineDelete(Machine* machine);
        OpMachineDelete* clone();
        
        unsigned int execute(Project& project);

    private:
        unsigned int id;        
};


// MACHINE GENERATED CODE BELOW, DO NOT EDIT
// USE COG TO REGENERATE

/*[[[cog

import os
import sys
sys.path.append(os.getcwd())
from codegen.op_specs import *

for line in machine_opgen.make_header():
    cog.outl(line)

]]]*/


class OpMachineName : public MachineChgOperation
{
    // AUTOGENERATED, DO NOT MODIFY
    public:
        OpMachineName(Machine* machine, string name);
        OpMachineName* clone();

        void execute_impl(Machine* machine);
        bool may_collapse_impl(Operation& other);
        void collapse(Operation& other);

    private:
        string name;
};


class OpMachineRunOnStart : public MachineChgOperation
{
    // AUTOGENERATED, DO NOT MODIFY
    public:
        OpMachineRunOnStart(Machine* machine, bool run_on_start);
        OpMachineRunOnStart* clone();

        void execute_impl(Machine* machine);
        bool may_collapse_impl(Operation& other);
        void collapse(Operation& other);

    private:
        bool run_on_start;
};

//[[[end]]]
