#include "state_ops.h"
#include "signals.h"


// Abstract modify
StateChgOperation::StateChgOperation(Machine* machine, State* state)
{
    machine_id = machine->id;
    state_id = state->id;
}


unsigned int StateChgOperation::execute(Project& project)
{
    Machine* machine = project.get_machine_by_id(machine_id);
    State* state = machine->get_state_by_id(state_id);
    execute_impl(state);
    signals.fire_model_changed(STATE, MODIFY, state_id);
    return state_id;
}


// Create

OpStateCreate::OpStateCreate(Machine* machine, float x, float y)
{
    machine_id = machine->id;
    this->x = x;
    this->y = y;
}


unsigned int OpStateCreate::execute(Project& project)
{
    State* state = new State(project.get_next_id());
    state->name = "new state";
    state->type = CODE;
    state->x = x;
    state->y = y;
    state->w = 150;
    state->h = 125;

    Machine* machine = project.get_machine_by_id(machine_id);
    machine->states.push_back(state);

    signals.fire_model_changed(STATE, CREATE, state->id);
    return state->id;
}


OpStateCreate* OpStateCreate::clone()
{
    return new OpStateCreate(*this);
}


// Delete

OpStateDelete::OpStateDelete(Machine* machine, State* state)
{
    machine_id = machine->id;
    state_id = state->id;
}


unsigned int OpStateDelete::execute(Project& project)
{
    Machine* machine = project.get_machine_by_id(machine_id);
    
    State* to_delete;
    int i;

    for(i=0; i<machine->states.size(); i++)
    {
        if(machine->states[i]->id == state_id)
        {
            to_delete = machine->states[i];
            break;
        }
    }

    signals.fire_model_changed(STATE, PRE_DELETE, state_id);

    // Unlink attached transitions
    for(int i=0; i<to_delete->incoming_transitions.size(); i++)
    {
        Transition* transition = to_delete->incoming_transitions[i];
        transition->to_state = nullptr;
        transition->update_positions();
    }

    for(int i=0; i<to_delete->outgoing_transitions.size(); i++)
    {
        Transition* transition = to_delete->outgoing_transitions[i];
        transition->from_state = nullptr;
        transition->update_positions();
    }

    delete to_delete;
    machine->states.erase(machine->states.begin() + i);
    return state_id;
}


OpStateDelete* OpStateDelete::clone()
{
    return new OpStateDelete(*this);
}


// Move

OpStateMove::OpStateMove(Machine* machine, State* state, float x, float y)
{
    machine_id = machine->id;
    state_id = state->id;
    this->x = x;
    this->y = y;
}


unsigned int OpStateMove::execute(Project& project)
{
    Machine* machine = project.get_machine_by_id(machine_id);
    State* state = machine->get_state_by_id(state_id);
    state->x = x;
    state->y = y;
    state->update_transition_positions();
    return state->id;
}


bool OpStateMove::may_collapse_impl(Operation& other)
{
    OpStateMove& other_move = dynamic_cast<OpStateMove&>(other);
    return other_move.state_id == state_id;
}


void OpStateMove::collapse(Operation& other)
{
    OpStateMove& other_move = dynamic_cast<OpStateMove&>(other);
    x = other_move.x;
    y = other_move.y;
}


OpStateMove* OpStateMove::clone()
{
    return new OpStateMove(*this);
}


// MACHINE GENERATED CODE BELOW, DO NOT EDIT
// USE COG TO REGENERATE

/*[[[cog

import os
import sys
sys.path.append(os.getcwd())
from codegen.op_specs import *

for line in state_opgen.make_cpp():
    cog.outl(line)

]]]*/


// type  -  AUTOGENERATED, DO NOT MODIFY

OpStateType::OpStateType(Machine* machine, State* state, StateType type) : StateChgOperation(machine, state)
{
    this->type = type;
}


OpStateType* OpStateType::clone()
{
    return new OpStateType(*this);
}


void OpStateType::execute_impl(State* state)
{
    state->type = type;
}


bool OpStateType::may_collapse_impl(Operation& other)
{
    auto op = (OpStateType&) other;
    return state_id == op.state_id;
}


void OpStateType::collapse(Operation& other)
{
    auto op = (OpStateType&) other;
    type = op.type;
}


// name  -  AUTOGENERATED, DO NOT MODIFY

OpStateName::OpStateName(Machine* machine, State* state, string name) : StateChgOperation(machine, state)
{
    this->name = name;
}


OpStateName* OpStateName::clone()
{
    return new OpStateName(*this);
}


void OpStateName::execute_impl(State* state)
{
    state->name = name;
}


bool OpStateName::may_collapse_impl(Operation& other)
{
    auto op = (OpStateName&) other;
    return state_id == op.state_id;
}


void OpStateName::collapse(Operation& other)
{
    auto op = (OpStateName&) other;
    name = op.name;
}


// code  -  AUTOGENERATED, DO NOT MODIFY

OpStateCode::OpStateCode(Machine* machine, State* state, string code) : StateChgOperation(machine, state)
{
    this->code = code;
}


OpStateCode* OpStateCode::clone()
{
    return new OpStateCode(*this);
}


void OpStateCode::execute_impl(State* state)
{
    state->code = code;
}


bool OpStateCode::may_collapse_impl(Operation& other)
{
    auto op = (OpStateCode&) other;
    return state_id == op.state_id;
}


void OpStateCode::collapse(Operation& other)
{
    auto op = (OpStateCode&) other;
    code = op.code;
}


// join_pid_variable  -  AUTOGENERATED, DO NOT MODIFY

OpStateJoinPidVariable::OpStateJoinPidVariable(Machine* machine, State* state, string join_pid_variable) : StateChgOperation(machine, state)
{
    this->join_pid_variable = join_pid_variable;
}


OpStateJoinPidVariable* OpStateJoinPidVariable::clone()
{
    return new OpStateJoinPidVariable(*this);
}


void OpStateJoinPidVariable::execute_impl(State* state)
{
    state->join_pid_variable = join_pid_variable;
}


bool OpStateJoinPidVariable::may_collapse_impl(Operation& other)
{
    auto op = (OpStateJoinPidVariable&) other;
    return state_id == op.state_id;
}


void OpStateJoinPidVariable::collapse(Operation& other)
{
    auto op = (OpStateJoinPidVariable&) other;
    join_pid_variable = op.join_pid_variable;
}


// join_result_variable  -  AUTOGENERATED, DO NOT MODIFY

OpStateJoinResultVariable::OpStateJoinResultVariable(Machine* machine, State* state, string join_result_variable) : StateChgOperation(machine, state)
{
    this->join_result_variable = join_result_variable;
}


OpStateJoinResultVariable* OpStateJoinResultVariable::clone()
{
    return new OpStateJoinResultVariable(*this);
}


void OpStateJoinResultVariable::execute_impl(State* state)
{
    state->join_result_variable = join_result_variable;
}


bool OpStateJoinResultVariable::may_collapse_impl(Operation& other)
{
    auto op = (OpStateJoinResultVariable&) other;
    return state_id == op.state_id;
}


void OpStateJoinResultVariable::collapse(Operation& other)
{
    auto op = (OpStateJoinResultVariable&) other;
    join_result_variable = op.join_result_variable;
}


// return_value  -  AUTOGENERATED, DO NOT MODIFY

OpStateReturnValue::OpStateReturnValue(Machine* machine, State* state, LVOV return_value) : StateChgOperation(machine, state)
{
    this->return_value = return_value;
}


OpStateReturnValue* OpStateReturnValue::clone()
{
    return new OpStateReturnValue(*this);
}


void OpStateReturnValue::execute_impl(State* state)
{
    state->return_value = return_value;
}


bool OpStateReturnValue::may_collapse_impl(Operation& other)
{
    auto op = (OpStateReturnValue&) other;
    return state_id == op.state_id;
}


void OpStateReturnValue::collapse(Operation& other)
{
    auto op = (OpStateReturnValue&) other;
    return_value = op.return_value;
}


// initial_args  -  AUTOGENERATED, DO NOT MODIFY

OpStateInitialArgs::OpStateInitialArgs(Machine* machine, State* state, vector<ArgDef> initial_args) : StateChgOperation(machine, state)
{
    this->initial_args = initial_args;
}


OpStateInitialArgs* OpStateInitialArgs::clone()
{
    return new OpStateInitialArgs(*this);
}


void OpStateInitialArgs::execute_impl(State* state)
{
    state->initial_args = initial_args;
}


bool OpStateInitialArgs::may_collapse_impl(Operation& other)
{
    auto op = (OpStateInitialArgs&) other;
    return state_id == op.state_id;
}


void OpStateInitialArgs::collapse(Operation& other)
{
    auto op = (OpStateInitialArgs&) other;
    initial_args = op.initial_args;
}


// launch_task_name  -  AUTOGENERATED, DO NOT MODIFY

OpStateLaunchTaskName::OpStateLaunchTaskName(Machine* machine, State* state, LVOV launch_task_name) : StateChgOperation(machine, state)
{
    this->launch_task_name = launch_task_name;
}


OpStateLaunchTaskName* OpStateLaunchTaskName::clone()
{
    return new OpStateLaunchTaskName(*this);
}


void OpStateLaunchTaskName::execute_impl(State* state)
{
    state->launch_task_name = launch_task_name;
}


bool OpStateLaunchTaskName::may_collapse_impl(Operation& other)
{
    auto op = (OpStateLaunchTaskName&) other;
    return state_id == op.state_id;
}


void OpStateLaunchTaskName::collapse(Operation& other)
{
    auto op = (OpStateLaunchTaskName&) other;
    launch_task_name = op.launch_task_name;
}


// launch_args  -  AUTOGENERATED, DO NOT MODIFY

OpStateLaunchArgs::OpStateLaunchArgs(Machine* machine, State* state, vector<Arg> launch_args) : StateChgOperation(machine, state)
{
    this->launch_args = launch_args;
}


OpStateLaunchArgs* OpStateLaunchArgs::clone()
{
    return new OpStateLaunchArgs(*this);
}


void OpStateLaunchArgs::execute_impl(State* state)
{
    state->launch_args = launch_args;
}


bool OpStateLaunchArgs::may_collapse_impl(Operation& other)
{
    auto op = (OpStateLaunchArgs&) other;
    return state_id == op.state_id;
}


void OpStateLaunchArgs::collapse(Operation& other)
{
    auto op = (OpStateLaunchArgs&) other;
    launch_args = op.launch_args;
}


// launch_result_variable  -  AUTOGENERATED, DO NOT MODIFY

OpStateLaunchResultVariable::OpStateLaunchResultVariable(Machine* machine, State* state, string launch_result_variable) : StateChgOperation(machine, state)
{
    this->launch_result_variable = launch_result_variable;
}


OpStateLaunchResultVariable* OpStateLaunchResultVariable::clone()
{
    return new OpStateLaunchResultVariable(*this);
}


void OpStateLaunchResultVariable::execute_impl(State* state)
{
    state->launch_result_variable = launch_result_variable;
}


bool OpStateLaunchResultVariable::may_collapse_impl(Operation& other)
{
    auto op = (OpStateLaunchResultVariable&) other;
    return state_id == op.state_id;
}


void OpStateLaunchResultVariable::collapse(Operation& other)
{
    auto op = (OpStateLaunchResultVariable&) other;
    launch_result_variable = op.launch_result_variable;
}


// launch_synchronous  -  AUTOGENERATED, DO NOT MODIFY

OpStateLaunchSynchronous::OpStateLaunchSynchronous(Machine* machine, State* state, bool launch_synchronous) : StateChgOperation(machine, state)
{
    this->launch_synchronous = launch_synchronous;
}


OpStateLaunchSynchronous* OpStateLaunchSynchronous::clone()
{
    return new OpStateLaunchSynchronous(*this);
}


void OpStateLaunchSynchronous::execute_impl(State* state)
{
    state->launch_synchronous = launch_synchronous;
}


bool OpStateLaunchSynchronous::may_collapse_impl(Operation& other)
{
    auto op = (OpStateLaunchSynchronous&) other;
    return state_id == op.state_id;
}


void OpStateLaunchSynchronous::collapse(Operation& other)
{
    auto op = (OpStateLaunchSynchronous&) other;
    launch_synchronous = op.launch_synchronous;
}


// has_return_value  -  AUTOGENERATED, DO NOT MODIFY

OpStateHasReturnValue::OpStateHasReturnValue(Machine* machine, State* state, bool has_return_value) : StateChgOperation(machine, state)
{
    this->has_return_value = has_return_value;
}


OpStateHasReturnValue* OpStateHasReturnValue::clone()
{
    return new OpStateHasReturnValue(*this);
}


void OpStateHasReturnValue::execute_impl(State* state)
{
    state->has_return_value = has_return_value;
}


bool OpStateHasReturnValue::may_collapse_impl(Operation& other)
{
    auto op = (OpStateHasReturnValue&) other;
    return state_id == op.state_id;
}


void OpStateHasReturnValue::collapse(Operation& other)
{
    auto op = (OpStateHasReturnValue&) other;
    has_return_value = op.has_return_value;
}


//[[[end]]]

